# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Data_Table = QtWidgets.QTableWidget(self.centralwidget)
        self.Data_Table.setObjectName("Data_Table")
        self.Data_Table.setColumnCount(0)
        self.Data_Table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.Data_Table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FN0_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.FN0_Delete.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FN0_Delete.setFont(font)
        self.FN0_Delete.setCheckable(False)
        self.FN0_Delete.setObjectName("FN0_Delete")
        self.horizontalLayout_2.addWidget(self.FN0_Delete)
        self.FN1_Modify = QtWidgets.QPushButton(self.centralwidget)
        self.FN1_Modify.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FN1_Modify.setFont(font)
        self.FN1_Modify.setObjectName("FN1_Modify")
        self.horizontalLayout_2.addWidget(self.FN1_Modify)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.End_Ctrl_Times = QtWidgets.QRadioButton(self.groupBox)
        self.End_Ctrl_Times.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.End_Ctrl_Times.setFont(font)
        self.End_Ctrl_Times.setObjectName("End_Ctrl_Times")
        self.gridLayout.addWidget(self.End_Ctrl_Times, 0, 1, 1, 1)
        self.End_Ctrl_Never = QtWidgets.QRadioButton(self.groupBox)
        self.End_Ctrl_Never.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.End_Ctrl_Never.setFont(font)
        self.End_Ctrl_Never.setChecked(True)
        self.End_Ctrl_Never.setObjectName("End_Ctrl_Never")
        self.gridLayout.addWidget(self.End_Ctrl_Never, 0, 0, 1, 1)
        self.End_Ctrl_date = QtWidgets.QRadioButton(self.groupBox)
        self.End_Ctrl_date.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.End_Ctrl_date.setFont(font)
        self.End_Ctrl_date.setObjectName("End_Ctrl_date")
        self.gridLayout.addWidget(self.End_Ctrl_date, 0, 2, 1, 1)
        self.Input_Enddate = QtWidgets.QDateEdit(self.groupBox)
        self.Input_Enddate.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Enddate.sizePolicy().hasHeightForWidth())
        self.Input_Enddate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Enddate.setFont(font)
        self.Input_Enddate.setTimeSpec(QtCore.Qt.LocalTime)
        self.Input_Enddate.setObjectName("Input_Enddate")
        self.gridLayout.addWidget(self.Input_Enddate, 1, 2, 1, 1)
        self.Input_Times = QtWidgets.QLineEdit(self.groupBox)
        self.Input_Times.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_Times.sizePolicy().hasHeightForWidth())
        self.Input_Times.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Times.setFont(font)
        self.Input_Times.setInputMask("")
        self.Input_Times.setMaxLength(32767)
        self.Input_Times.setObjectName("Input_Times")
        self.gridLayout.addWidget(self.Input_Times, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 1, 1, 1)
        self.Input_Title = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Title.setFont(font)
        self.Input_Title.setObjectName("Input_Title")
        self.gridLayout_2.addWidget(self.Input_Title, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.Input_Startdate = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Startdate.setFont(font)
        self.Input_Startdate.setCalendarPopup(True)
        self.Input_Startdate.setObjectName("Input_Startdate")
        self.gridLayout_2.addWidget(self.Input_Startdate, 1, 1, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName("groupBox1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Loop_Ctrl_Never = QtWidgets.QRadioButton(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Loop_Ctrl_Never.setFont(font)
        self.Loop_Ctrl_Never.setChecked(True)
        self.Loop_Ctrl_Never.setObjectName("Loop_Ctrl_Never")
        self.horizontalLayout_3.addWidget(self.Loop_Ctrl_Never)
        self.Loop_Ctrl_Day = QtWidgets.QRadioButton(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Loop_Ctrl_Day.setFont(font)
        self.Loop_Ctrl_Day.setObjectName("Loop_Ctrl_Day")
        self.horizontalLayout_3.addWidget(self.Loop_Ctrl_Day)
        self.Loop_Ctrl_Week = QtWidgets.QRadioButton(self.groupBox1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Loop_Ctrl_Week.setFont(font)
        self.Loop_Ctrl_Week.setObjectName("Loop_Ctrl_Week")
        self.horizontalLayout_3.addWidget(self.Loop_Ctrl_Week)
        self.Loop_Ctrl_Month = QtWidgets.QRadioButton(self.groupBox1)
        self.Loop_Ctrl_Month.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Loop_Ctrl_Month.setFont(font)
        self.Loop_Ctrl_Month.setCheckable(True)
        self.Loop_Ctrl_Month.setObjectName("Loop_Ctrl_Month")
        self.horizontalLayout_3.addWidget(self.Loop_Ctrl_Month)
        self.Loop_Ctrl_Year = QtWidgets.QRadioButton(self.groupBox1)
        self.Loop_Ctrl_Year.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Loop_Ctrl_Year.setFont(font)
        self.Loop_Ctrl_Year.setObjectName("Loop_Ctrl_Year")
        self.horizontalLayout_3.addWidget(self.Loop_Ctrl_Year)
        self.gridLayout_2.addWidget(self.groupBox1, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Duration_Ctrl = QtWidgets.QCheckBox(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Duration_Ctrl.setFont(font)
        self.Duration_Ctrl.setObjectName("Duration_Ctrl")
        self.horizontalLayout_5.addWidget(self.Duration_Ctrl)
        self.Input_Duration_hours = QtWidgets.QSpinBox(self.horizontalGroupBox)
        self.Input_Duration_hours.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Duration_hours.setFont(font)
        self.Input_Duration_hours.setMaximum(10)
        self.Input_Duration_hours.setObjectName("Input_Duration_hours")
        self.horizontalLayout_5.addWidget(self.Input_Duration_hours)
        self.label_6 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.Input_Duration_minutes = QtWidgets.QSpinBox(self.horizontalGroupBox)
        self.Input_Duration_minutes.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Duration_minutes.setFont(font)
        self.Input_Duration_minutes.setMaximum(59)
        self.Input_Duration_minutes.setObjectName("Input_Duration_minutes")
        self.horizontalLayout_5.addWidget(self.Input_Duration_minutes)
        self.label_7 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.Input_Duration_seconds = QtWidgets.QSpinBox(self.horizontalGroupBox)
        self.Input_Duration_seconds.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Input_Duration_seconds.setFont(font)
        self.Input_Duration_seconds.setMaximum(59)
        self.Input_Duration_seconds.setObjectName("Input_Duration_seconds")
        self.horizontalLayout_5.addWidget(self.Input_Duration_seconds)
        self.label_8 = QtWidgets.QLabel(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.gridLayout_2.addWidget(self.horizontalGroupBox, 4, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.FN2_Add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FN2_Add.sizePolicy().hasHeightForWidth())
        self.FN2_Add.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FN2_Add.setFont(font)
        self.FN2_Add.setObjectName("FN2_Add")
        self.verticalLayout_2.addWidget(self.FN2_Add)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 4)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Result_View = QtWidgets.QTextBrowser(self.centralwidget)
        self.Result_View.setObjectName("Result_View")
        self.verticalLayout.addWidget(self.Result_View)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setMinimumSize(QtCore.QSize(0, 0))
        self.tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab.setObjectName("tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_4.addWidget(self.textBrowser_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.FN0_Delete)
        MainWindow.setTabOrder(self.FN0_Delete, self.FN1_Modify)
        MainWindow.setTabOrder(self.FN1_Modify, self.Input_Startdate)
        MainWindow.setTabOrder(self.Input_Startdate, self.Loop_Ctrl_Day)
        MainWindow.setTabOrder(self.Loop_Ctrl_Day, self.Loop_Ctrl_Never)
        MainWindow.setTabOrder(self.Loop_Ctrl_Never, self.Loop_Ctrl_Week)
        MainWindow.setTabOrder(self.Loop_Ctrl_Week, self.Loop_Ctrl_Year)
        MainWindow.setTabOrder(self.Loop_Ctrl_Year, self.Loop_Ctrl_Month)
        MainWindow.setTabOrder(self.Loop_Ctrl_Month, self.FN2_Add)
        MainWindow.setTabOrder(self.FN2_Add, self.Input_Title)
        MainWindow.setTabOrder(self.Input_Title, self.Result_View)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FN0_Delete.setText(_translate("MainWindow", "删除选中"))
        self.FN1_Modify.setText(_translate("MainWindow", "修改选中"))
        self.End_Ctrl_Times.setText(_translate("MainWindow", "按次数"))
        self.End_Ctrl_Never.setText(_translate("MainWindow", "不终止"))
        self.End_Ctrl_date.setText(_translate("MainWindow", "按时间"))
        self.Input_Times.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "事件描述"))
        self.Input_Startdate.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss dddd"))
        self.Loop_Ctrl_Never.setText(_translate("MainWindow", "不循环"))
        self.Loop_Ctrl_Day.setText(_translate("MainWindow", "每日"))
        self.Loop_Ctrl_Week.setText(_translate("MainWindow", "每周"))
        self.Loop_Ctrl_Month.setText(_translate("MainWindow", "每月"))
        self.Loop_Ctrl_Year.setText(_translate("MainWindow", "每年"))
        self.label_3.setText(_translate("MainWindow", "是否循环"))
        self.label_2.setText(_translate("MainWindow", "开始时间"))
        self.label_4.setText(_translate("MainWindow", "是否终止"))
        self.label_5.setText(_translate("MainWindow", "持续时间"))
        self.Duration_Ctrl.setText(_translate("MainWindow", "启用"))
        self.label_6.setText(_translate("MainWindow", "小时"))
        self.label_7.setText(_translate("MainWindow", "分钟"))
        self.label_8.setText(_translate("MainWindow", "秒"))
        self.FN2_Add.setText(_translate("MainWindow", "添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
